name: tarea6_couteau
description: Aplicación para la asignación de toolbox
publish_to: 'none' 

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  url_launcher: ^6.2.5
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/toolbox.png
    - assets/xaviel_foto.jpg
    - assets/young.png
    - assets/adult.png
    - assets/old.png
    - assets/wordpress_logo.png
    - assets/audio/pokemon.mp3
